name: Wake Up My Streamlit App
on:
  schedule:
    # Chạy mỗi 4 tiếng một lần (đảm bảo app luôn thức)
    - cron: '0 */4 * * *'
  workflow_dispatch: # Cho phép bạn bấm nút chạy thử thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I https://quan-ly-don-vi-fjkqqt42dehhosixg4r3zy.streamlit.app
